name: Build23

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fileName: "starter_linux"
          - os: windows-latest
            fileName: "starter_windows.exe"
          - os: macos-latest
            fileName: "starter_macos"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Build
        run: dart compile exe ./bin/launcher_bootstrap.dart -o ${{ matrix.fileName }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ matrix.fileName }}
